Document: typical-package-set-askh
Title: Debian typical-package-set-askh Manual
Author: <insert document author here>
Abstract: This manual describes what typical-package-set-askh is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/typical-package-set-askh/typical-package-set-askh.sgml.gz

Format: postscript
Files: /usr/share/doc/typical-package-set-askh/typical-package-set-askh.ps.gz

Format: text
Files: /usr/share/doc/typical-package-set-askh/typical-package-set-askh.text.gz

Format: HTML
Index: /usr/share/doc/typical-package-set-askh/html/index.html
Files: /usr/share/doc/typical-package-set-askh/html/*.html
